config/routes.rb
Rails.application.routes.draw do
  resources :questions
  get 'questions/:id/submit_answer', to: 'questions#submit_answer', as: 'submit_answer'
  resources :chapters
  resources :results
  resources :users
  namespace :admin do
    root to: "chapters#index"
    resources :chapters
    resources :questions
  end
root 'users#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question

	validates :body, presence: true
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
	has_many :questions
end

app/models/given_answer.rb
class GivenAnswer < ActiveRecord::Base
	belongs_to :answer
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :chapter
	has_many :answers, :dependent => :destroy
	has_many :results
	accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:body].blank? }, :allow_destroy => true

	after_create :set_right_answer

	def set_right_answer
		self.right_answer_id = self.answers.first.id
		self.save
	end
	validates :body, :explanation, presence: true
end

app/models/result.rb
class Result < ActiveRecord::Base
	belongs_to :question
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/admin/chapters_controller.rb
class Admin::ChaptersController < ApplicationController
	layout 'admin'
  	before_filter :admin_required
	def index
		@chapter = Chapter.all
	end

	def new
		@chapter = Chapter.new
	end

	def create
		chapter = Chapter.new(chapter_params)

		flash[:notice] = "Het hoofdstuk is succesvol toegevoegd !"
		chapter.save
		redirect_to admin_chapters_path
	end
	def edit
		@chapter = Chapter.find(params[:id])
	end
	def update
		@chapter = Chapter.find(params[:id])
		@chapter.update(chapter_params)
		redirect_to admin_chapters_path
	end
	def destroy
		flash[:notice] = "Het hoofdstuk is succesvol verwijderd !"
		@chapter = Chapter.find(params[:id])
		@chapter.destroy
		redirect_to admin_chapters_path
	end
	private
		def chapter_params
			params.require(:chapter).permit(:body)
		end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
	layout 'admin'
  	before_filter :admin_required
	def index
		@question = Question.order("id desc")
		@question.build()
	end
	def new
		@question = Question.new
		@chapter = Chapter.all
		4.times { @question.answers.build }
	end
	def edit
		@question = Question.find(params[:id])
	end
	def create
		@question = Question.new(question_params)

		if @question.save
			flash[:notice] = "Uw vraag is succesvol opgeslagen !"
			redirect_to admin_questions_path
		else
			render 'new'
		end
	end
	def update
		@question = Question.find(params[:id])
		if @question.update(question_params)
			flash[:notice] = "De vraag is succesvol gewijzigd !"
			redirect_to admin_questions_path
		else
			4.times { @question.answers.build }
			render 'new'
		end
	end
	def show
		@question = Question.find(params[:id])
		@answer = Answer.all
	end 
	def destroy
		@question = Question.find(params[:id])
		if @question.destroy

			flash[:notice] = "De vraag is succesvol verwijderd"
			@question.destroy
		else

			flash[:notice] = "Er is iets verkeerds gegaan"
		end
		redirect_to admin_questions_path
	end
	private
		def question_params
			params.require(:question).permit( :body, :chapter_id, :explanation, answers_attributes: [:id, :body])
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

	protect_from_forgery with: :exception
	protected
		def admin_required
		authenticate_or_request_with_http_basic do |username, password|
		username == "user" && password == "user"
		end
	end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
end

app/controllers/explanations_controller.rb
class ExplanationsController < ApplicationController
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def index
		@question = Question.all
	end

	def show
		if params[:answer_id].present?
			@question = Question.find(params[:id])
			@answer = Answer.find(@question.right_answer_id)
			@given_answer = Answer.find(params[:answer_id])
		else
			@question = Question.order('RANDOM()').first
			@answer = @question.answers.shuffle
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/admin/chapters_helper.rb
module Admin::ChaptersHelper
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/explanations_helper.rb
module ExplanationsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/answers/_answer_fields.html.haml
.form-group
	= f.text_field :body, class: "form-control", placeholder: "Antwoord"

app/views/admin/chapters/_form.html.haml
%br
.col-md-6
	.panel.panel-primary
		.panel-heading 
			%b Nieuw hoofdstuk toevoegen
		.panel-body
			= form_for [:admin, chapter] do |f|
				.form-group
					= f.text_field :body, class: "form-control", placeholder: "bijv. Hoofdstuk 1"
				.form-group
					= f.submit 'Opslaan', class: "btn btn-primary pull-right"

app/views/admin/chapters/edit.html.haml
= render 'form', chapter: @chapter

app/views/admin/chapters/index.html.haml
%h1 Hoofdstukken overzicht
= link_to "Nieuw hoofdstuk toevoegen", new_admin_chapter_path, class: "btn btn-primary"
.row
	.col-md-12
		%br
		-if flash[:notice]
			.alert.alert-success
				= flash[:notice]
.panel.panel-info
	.panel-heading 
		%b Alle hoofdstukken
	%table.table.table-striped
		- @chapter.each do |c|
			%tr
				%td.col-md-12= c.body
				%td.col-md-0= link_to "Bewerken", edit_admin_chapter_path(c), class: "btn btn-warning"
				%td.col-md-0= link_to 'Verwijderen', admin_chapter_path(c), method: :delete, data: {confirm: 'Zeker weten?'}, class: 'btn btn-danger'

app/views/admin/chapters/new.html.haml
= render 'form', chapter: @chapter

app/views/admin/questions/_form.html.haml
.col-md-8
	.panel.panel-primary
		.panel-heading Nieuwe vraag toevoegen
		.panel-body

			= form_for [:admin, question] do |f|
				- if @question.errors.any?
					%ul
						- for message in @question.errors.full_messages
							%li= message 
             
				.form-group
					= f.collection_select(:chapter_id, Chapter.all, :id, :body, class: "form-control")
				.form-group
					= f.text_area :body, rows: "5" , class: "form-control", placeholder: "Vraag"
				%label Het eerste antwoord word als goede antwoord opgeslagen
				= f.fields_for :answers do |a|
					= render "admin/answers/answer_fields", :f => a

				.form-group.has-success
					= f.text_area :explanation, rows: "3" , class: "form-control", placeholder: "Toelichting"
				.form-group
					= f.submit 'Opslaan', class: "btn btn-primary pull-right"

app/views/admin/questions/edit.html.haml
= render "form", question: @question

app/views/admin/questions/index.html.haml
%h1 Vragen overzicht
= link_to "Nieuwe vraag toevoegen", new_admin_question_path, class: "btn btn-primary"
%br
%br

-if flash[:notice]
	.alert.alert-success
		= flash[:notice]
.panel.panel-info
	.panel-heading 
		%b Alle vragen
	%table.table.table-striped
		%tr
			%td.col-sm-2 Hoofdstuk
			%td.col-sm-10 Vraag
			%td
			%td
			%td
		- @question.each do |q|
			%tr
				%td
					%span.label.label-success= q.chapter.body.first(13)
				%td= q.body
				%td= link_to 'Bekijk', admin_question_path(q), class: 'btn btn-info'
				%td= link_to 'Wijzig', edit_admin_question_path(q), class: 'btn btn-warning'
				%td= link_to 'Verwijderen', admin_question_path(q), method: :delete, data:{confirm: "Weet u het zeker ?"}, class: 'btn btn-danger'

app/views/admin/questions/new.html.haml
= render "form", question: @question

app/views/admin/questions/show.html.haml
%br
.col-md-7
	.panel.panel-info
		.panel-heading 
			%b Vraag
		.panel-body
			.row
				.col-md-12
					%b Hoofdstuk
					.well.well-sm
						%b= @question.chapter.body
			.row
				.col-md-12
					%b Vraag
					
					
					.well.well-sm
						%b= @question.body

			.row
				.col-md-12
					%b Mogelijke antwoorden
					- for answer in @question.answers
						.panel.panel-default
							.panel-body
								=h answer.body
			.row
				.col-md-12
					%b Goede antwoord
					%h4
						%span.label.label-success= Answer.find(@question.right_answer_id).body
			.row
				.col-md-12
					%b Toelichting
					.alert.alert-success
						= @question.explanation
			.row
				.col-md-12
					= link_to 'Wijzig', edit_admin_question_path(params[:id]), class: 'btn btn-warning pull-right'
					= link_to 'Verwijderen', admin_question_path(params[:id]), method: :delete, data:{confirm: "Weet u het zeker?"}, class: 'btn btn-danger'

app/views/chapters/index.html.haml
.col-md-4
	.panel.panel-primary
		.panel-heading 4. Hoofdstuk keuze
		.panel-body
			.row
				.nav
					%a=link_to "< menu", root_path
			.row
				=image_tag "QuizLogo_110-50px-150dpi.png", class: "logo"
			.row
				=link_to "Hoofdstuk 1", question_path, class: "true"
				-#=link_to root_path, remote: true do
				-#	%input{:type=>"button", class: "true", value: "Hoofdstuk 1"}
			.row
				=link_to "Hoofdstuk 2", question_path(0), class: "true"
				-#%input{:type=>"button", class: "not-available", value: "Hoofdstuk 2"}
			.row
				%input{:type=>"button", class: "not-available", value: "Hoofdstuk 3"}
			.row
				%input{:type=>"button", class: "not-available", value: "Hoofdstuk 4"}

app/views/questions/index.html.haml
.col-md-4
	.panel-body
		.row
			.nav
				%a=link_to "< home", root_path
		.row
			=image_tag "Logo_200px.png", class: "logo"
		.row
			=link_to question_path(0) do
				%input{:type=>"button", class: "true", value: "Hoofdstuk 1"}				
		.row
			%input{:type=>"button", class: "not-available", value: "Hoofdstuk 2"}
		.row
			%input{:type=>"button", class: "not-available", value: "Hoofdstuk 3"}
		.row
			%input{:type=>"button", class: "not-available", value: "Hoofdstuk 4"}
		.row
			%input{:type=>"button", class: "not-available", value: "Hoofdstuk 5"}
		.row
			%input{:type=>"button", class: "not-available", value: "Hoofdstuk 6"}
		.row
			%input{:type=>"button", class: "not-available", value: "Hoofdstuk 7"}
		.row
			%input{:type=>"button", class: "not-available", value: "Hoofdstuk 8"}
		.row
			%input{:type=>"button", class: "not-available", value: "Hoofdstuk 9"}
		.row
			%input{:type=>"button", class: "not-available", value: "Hoofdstuk 10"}
		.row
			%input{:type=>"button", class: "not-available", value: "Hoofdstuk 11"}
		.row
			%input{:type=>"button", class: "not-available", value: "Hoofdstuk 12"}

app/views/questions/show.html.haml
.col-md-12
	.panel-body
		.row
			.nav
				%a=link_to "< menu", questions_path
				=image_tag "Beeldmerk_30px.png", class: "pull-right", id: "beeldmerk"
				#chapter-number Hoofdstuk 1
				%br
				#chapter-title Hoe leren leerlingen

		.questions= @question.body
		%table

			- if params[:answer_id] == "#{@question.right_answer_id}"
				
				%b Het goede antwoord is:
				%br
				.alert.alert-success
					= @answer.body
				.alert.alert-warning
					%b Uitleg:
					%br
					= @question.explanation

				= link_to 'Volgende', question_path(0), class: 'btn btn-success pull-right'


			- elsif params[:answer_id] && params[:answer_id].present? != "#{@question.right_answer_id}"

				%b Het goede antwoord is:
				%br
				.alert.alert-success
					= @answer.body
				%b U gegeven antwoord:
				%br
				.alert.alert-danger
					= @given_answer.body

				%b Uitleg: 
				%br
				.alert.alert-warning
					= @question.explanation

				= link_to 'Volgende', question_path(0), class: 'btn btn-success pull-right'
			-else
				%tr
					- @answer.each do |a|
						.answer		
							= link_to (a.body), question_path(@question, answer_id: a.id), class: "btn btn-default"

app/views/users/index.html.haml
.col-md-4
	.panel-body
		-#.row
		-#	.nav
		-#		%a
		-#			=link_to "Inloggen", chapters_path, class: "pull-right"
		.row
			=image_tag "Logo_200px.png", class: "logo", id: "logo-frontpage"
		.row
			=link_to questions_path do
				%input{:type=>"button", class: "button-intro", value: "Starten"}
		#intro
			="Toets jou kennis over het boek"
			#intro-title 'Handboek voor Leraren'
		.row
			- text = "Auteurs \n Walter Geerts en René van Kralingen"
			.p= find_and_preserve text.split("\n").join('<br>')

app/views/users/login.html.haml
.col-md-4
	.panel.panel-primary
		.panel-heading 3. Inloggen
		.panel-body
			.row
				.nav
					%a < home
			.row
				=image_tag "QuizLogo.png", class: "logo"
			.row
				%label{:for=>"gebruikersnaam"} Gebruikersnaam
				%input{:type=>"text", :id=>"gebruikersnaam"}

			.row
				%label{:for=>"password"} Wachtwoord
				%input{:type=>"password", :id=>"password"}

			.row
				%input{:type=>"button", class: "true-smallest", value: "Inloggen"}

app/views/users/new.html.haml
.col-md-4
	.panel.panel-primary
		.panel-heading 2. Account aanmaken
		.panel-body
			.row
				.nav
					%a=link_to "< home", root_path

			.row
				%label.item-2{:for=>"voornaam"} Voornaam
				%label.item-2.right{:for=>"achternaam"} Achternaam
				%input{:type=>"text", :class=>"item-2", :id=>"voornaam"}
				%input{:type=>"text", :class=>"item-2 right", :id=>"achternaam"}

			.row
				%label{:for=>"email"} Email
				%input{:type=>"text", :id=>"email"}
			
			.row
				%label{:for=>"gebruikersnaam"} Gebruikersnaam
				%input{:type=>"text", :id=>"gebruikersnaam"}

			.row
				%label{:for=>"password"} Wachtwoord
				%input{:type=>"password", :id=>"password"}

			.row
				%label{:for=>"repeat-password"} Herhaal wachtwoord
				%input{:type=>"password", :id=>"repeat-password"}

			.row
				%input{:type=>"button", class: "true-smallest", value: "Opslaan"}