config/routes.rb
Rails.application.routes.draw do
  resources :questions
  get 'questions/:id/submit_answer', to: 'questions#submit_answer', as: 'submit_answer'
  resources :chapters
  resources :results
  resources :users
  namespace :admin do
    root to: "chapters#index"
    resources :chapters
    resources :questions
  end
root 'users#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question

	validates :body, presence: true
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
	has_many :questions
end

app/models/given_answer.rb
class GivenAnswer < ActiveRecord::Base
	belongs_to :answer
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :chapter
	has_many :answers, :dependent => :destroy
	has_many :results
	accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:body].blank? }, :allow_destroy => true

	after_create :set_right_answer

	def set_right_answer
		self.right_answer_id = self.answers.first.id
		self.save
	end
	validates :body, :explanation, presence: true
end

app/models/result.rb
class Result < ActiveRecord::Base
	belongs_to :question
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/admin/chapters_controller.rb
class Admin::ChaptersController < ApplicationController
	layout 'admin'
  	before_filter :admin_required
	def index
		@chapter = Chapter.all
	end

	def new
		@chapter = Chapter.new
	end

	def create
		chapter = Chapter.new(chapter_params)

		flash[:notice] = "Het hoofdstuk is succesvol toegevoegd !"
		chapter.save
		redirect_to admin_chapters_path
	end
	def edit
		@chapter = Chapter.find(params[:id])
	end
	def update
		@chapter = Chapter.find(params[:id])
		@chapter.update(chapter_params)
		redirect_to admin_chapters_path
	end
	def destroy
		flash[:notice] = "Het hoofdstuk is succesvol verwijderd !"
		@chapter = Chapter.find(params[:id])
		@chapter.destroy
		redirect_to admin_chapters_path
	end
	private
		def chapter_params
			params.require(:chapter).permit(:body)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

	protect_from_forgery with: :exception
	protected
		def admin_required
		authenticate_or_request_with_http_basic do |username, password|
		username == "user" && password == "user"
		end
	end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
end

app/controllers/explanations_controller.rb
class ExplanationsController < ApplicationController
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def index
		@question = Question.all
	end

	def show
		if params[:answer_id].present?
			@question = Question.find(params[:id])
			@answer = Answer.find(@question.right_answer_id)
			@given_answer = Answer.find(params[:answer_id])
		else
			@question = Question.order('RANDOM()').first
			@answer = @question.answers.shuffle
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/admin/chapters_helper.rb
module Admin::ChaptersHelper
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/explanations_helper.rb
module ExplanationsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/1application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuizVoorLeraren</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/admin.html.haml
!!!
%html
	%head
		%title Leraren Quiz

		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true

    
		= csrf_meta_tags
  
	%body
		
		.col-sm-2
			%br
			.row
				.col-sm-12
					=image_tag "QuizLogo_110-50px-72dpi.png"
			%br
			.row
				.col-sm-12
					#menu
						%ul.list-group
							%li.list-group-item.list-group-item-info
								%b Menu
							%li.list-group-item
								%a 
									= link_to 'Vragen overzicht', admin_questions_url
							%li.list-group-item
								%a 
									= link_to 'Hoofdstukken overzicht', admin_chapters_url
		.col-sm-10

			= yield

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title Leraren Quiz

		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true

    
		= csrf_meta_tags
  
	%body
		.col-sm-12
			= yield